_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  WEIGHTS: "./output/pmmv2/R_101/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 5
DATASETS:
  TRAIN: ("318_novel_10_shot_train",)
  TEST: ("318_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (4000, 5000)
  MAX_ITER: 5000
  WARMUP_ITERS: 20
  CHECKPOINT_PERIOD: 2000
INPUT:
  FS:
    FEW_SHOT: True
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 19
  MIN_SIZE_TRAIN: (440, 472, 504, 536, 568, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
OUTPUT_DIR: './output/pmmv2/R_101/'

